INSERT INTO `diagnoses` (`Diagnosis_ID`, `DiagnosisName`, `DiagnosisClass`) VALUES
(1, 'AFP (Polio)', 'communicable immunizable'),
(2, 'Meningitis', 'communicable immunizable'),
(3, 'Neo-Natal Tetanus', 'communicable immunizable'),
(4, 'Pertussis (Whooping Cough)', 'communicable immunizable'),
(5, 'Diphteria', 'communicable immunizable'),
(6, 'Measles', 'communicable immunizable'),
(7, 'Yellow Fever', 'communicable immunizable'),
(8, 'Tetanus', 'communicable immunizable'),
(9, 'Tuberculosis', 'communicable immunizable'),
(10, 'Uncomplicated Malaria', 'communicable non-immunizable'),
(11, 'Severe Malaria', 'communicable non-immunizable'),
(12, 'Typhoid Fever', 'communicable non-immunizable'),
(13, 'Cholera', 'communicable non-immunizable'),
(14, 'Diarrhoea Diseases(Enteritis,Gastroenteritis,Diarrhoea)', 'communicable non-immunizable'),
(15, 'Viral Hepatitis', 'communicable non-immunizable'),
(16, 'Schistosomiasis(Bilhazia)', 'communicable non-immunizable'),
(17, 'Guinea Worm', 'communicable non-immunizable'),
(18, 'Onchocerciasis', 'communicable non-immunizable'),
(19, 'Buruli Ulcer', 'communicable non-immunizable'),
(20, 'Leprosy', 'communicable non-immunizable'),
(21, 'Infectious Yaws', 'communicable non-immunizable'),
(22, 'HIV/AIDS', 'communicable non-immunizable'),
(23, 'Mumps', 'communicable non-immunizable'),
(24, 'Helminthiasis', 'communicable non-immunizable'),
(25, 'Chicken Pox', 'communicable non-immunizable'),
(26, 'Upper Respiratory Tract Infections(URTI,LRTI,RTI)', 'communicable non-immunizable'),
(27, 'Pneumonia', 'communicable non-immunizable'),
(28, 'Septiceamia', 'communicable non-immunizable'),
(29, 'Malnutrition', 'non-communicable'),
(30, 'Obesity', 'non-communicable'),
(31, 'Anaemia', 'non-communicable'),
(32, 'Other Nutritional Diseases', 'non-communicable'),
(33, 'Hypertension', 'non-communicable'),
(34, 'Cardiac Diseases', 'non-communicable'),
(35, 'Stroke', 'non-communicable'),
(36, 'Diabetes Mellitus', 'non-communicable'),
(37, 'Rheumatism & Other Joint Pains(Arthritis,Lumbago,Musculoskeletal Pains, Arthralgia, Cephalgia, Spondylosis)', 'non-communicable'),
(38, 'Sickle Cell Disease', 'non-communicable'),
(39, 'Asthma', 'non-communicable'),
(40, 'Chronic Obstructed Pulmonary Disease (COPD)', 'non-communicable'),
(41, 'Breast Cancer', 'non-communicable'),
(42, 'Cervical Cancer', 'non-communicable'),
(43, 'Lymphoma', 'non-communicable'),
(44, 'Prostate Cancer', 'non-communicable'),
(45, 'Hepatocellular Carcinoma', 'non-communicable'),
(46, 'All Other Cancers', 'non-communicable'),
(47, 'Schizophrenia', 'mental health'),
(48, 'Acute Psychotic Disorder', 'mental health'),
(49, 'Mono Symptoms Delusion', 'mental health'),
(50, 'Depression', 'mental health'),
(51, 'Substance Abuse', 'mental health'),
(52, 'Epilepsy', 'mental health'),
(53, 'Autism', 'mental health'),
(54, 'Mental Retardation', 'mental health'),
(55, 'Attention Deficit Hyperactivity Disorder', 'mental health'),
(56, 'Conversion Disorder', 'mental health'),
(57, 'Post Traumatic Stress Syndrome', 'mental health'),
(58, 'Generalized Anxiety', 'mental health'),
(59, 'Other Anxiety Disorders', 'mental health'),
(60, 'Neurosis', 'mental health'),
(61, 'Acute Eye Infection/Conjunctivitis', 'specialized'),
(62, 'Cataract', 'specialized'),
(63, 'Trachoma', 'specialized'),
(64, 'Otitis Media', 'specialized'),
(65, 'Other Acute Ear Infection', 'specialized'),
(66, 'Dental Caries', 'specialized'),
(67, 'Dental Swellings', 'specialized'),
(68, 'Traumtic Conditions (Oral and Maxillofacial Region)', 'specialized'),
(69, 'Peridontal diseases', 'specialized'),
(70, 'Cerebral Palsy', 'specialized'),
(71, 'Liver Diseases', 'specialized'),
(72, 'Acute Urinary Tract Infection(UTI)', 'specialized'),
(73, 'Skin Diseases/Dermatitits', 'specialized'),
(74, 'Ulcer/Wounds/Lacerations/Circumcisions', 'specialized'),
(75, 'Kidney Related Diseases', 'specialized'),
(76, 'Other Oral Conditions', 'specialized'),
(78, 'Pregnancy Related Complications', 'obstetric & gynaecological'),
(79, 'Gonorrhoea', 'reproductive tract'),
(80, 'Genital Ulcer', 'reproductive tract'),
(81, 'Vaginal Discharge/Syphilis', 'reproductive tract'),
(82, 'Urethral Discharge', 'reproductive tract'),
(83, 'Other diseases of the Male reproductive system', 'reproductive tract'),
(84, 'Other diseases of the Female reproductive system', 'reproductive tract'),
(85, 'Transport injuries (Road Traffic Accidents)', 'injuries'),
(86, 'Home Injuries (Home Accidents and Injuries)', 'injuries'),
(87, 'Occupational Injuries', 'injuries'),
(88, 'Burns', 'injuries'),
(89, 'Poisoning (Occupational Poisoning)', 'injuries'),
(90, 'Dog Bite', 'injuries'),
(91, 'Human Bites', 'injuries'),
(92, 'Snake Bite', 'injuries'),
(93, 'Sexual Abuse', 'injuries'),
(94, 'Domestic Violence', 'injuries'),
(96, 'Other Animal Bites', 'injuries'),
(97, 'Pyrexia of unknown origin PUO (not Malaria)', 'others'),
(98, 'Brought in Dead', 'others'),
(99, 'All other Cases', 'others');

